export const GET_CURRENT_WEATHER_SUCCESS = 'GET_CURRENT_WEATHER_SUCCESS';
export const GET_CURRENT_WEATHER_LOADING = 'GET_CURRENT_WEATHER_LOADING';

export const GET_FORECAST_WEATHER_SUCCESS = 'GET_FORECAST_WEATHER_SUCCESS';
export const GET_FORECAST_WEATHER_LOADING = 'GET_FORECAST_WEATHER_LOADING';